In [1]:
import numpy as np
import pandas as pd

In [2]:
#1) Examen
print("Examen")


Examen


In [3]:
#2) Crear un vector de ceros de tamaño 10
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_ceros_con_uno = np.zeros(10)
vector_ceros_con_uno[5]=1
vector_ceros_con_uno

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [6]:
#4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50, etc
vector_fifty_elements = np.arange(51)[::-1]
vector_fifty_elements

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
#5) Crear una matriz de 3x3 con valores del 0 al 8
matriz_3_3 = np.arange(9).reshape(3,3)
matriz_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
#6) Encontrar los indices que no sean 0 en un arreglo
arreglo = [1,2,0,0,4,0]
arreglo_np = np.array(arreglo)
arreglo_no_ceros = arreglo_np[(arreglo_np>0)]
arreglo_no_ceros

array([1, 2, 4])

In [22]:
#7) Crear una matriz identidad de 3x3
matriz_identidad_3_3 = np.eye(3)
matriz_identidad_3_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#8) Crear una matriz 3x3x3 con valores randómicos
matriz_3_3_random = np.random.randint(0,100,27).reshape(3,3,3)
matriz_3_3_random

array([[[88, 13, 78],
        [69, 21,  2],
        [35, 85, 98]],

       [[37, 51, 83],
        [94, 77, 35],
        [41, 83, 82]],

       [[56, 87, 26],
        [20, 98,  4],
        [85, 24,  8]]])

In [43]:
#9) Crear una matriz 10x10 y encontrar el mayor y el menor
matriz_10_10 = np.random.randint(0,200,100).reshape(10,10)
print(matriz_10_10)
print(f"Mayor: {matriz_10_10.max()}")
print(f"Menor: {matriz_10_10.min()}")

[[169  18  15  95  28 118  58 167  32 126]
 [108  44 132  13  42 130 155  48  29  15]
 [ 97 133  75   2 137  54  40 199 164 180]
 [ 32  27  55  79   8  61 166 158  25 107]
 [178 154  57  72 161  21 102   4  74  66]
 [105  22 165  44 107  90  12  23 192  23]
 [189  33  50 160 147  82 181 179  83 161]
 [101  40   6  13  56  97 191  68  16 155]
 [152 136  11  86 191 137  39 197  86 139]
 [157 136 139 118 102 161 194   7  54 192]]
Mayor: 199
Menor: 2


In [ ]:
#10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)


In [49]:
#11) ¿Como crear una serie de una lista, diccionario o arreglo?
mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist,myarr))
serie_lista = pd.Series(mylist)
serie_arr = pd.Series(myarr)
serie_dict = pd.Series(mydict)
serie_dict

a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [53]:
# 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
dataframe = pd.DataFrame(ser.index, index=myarr[::-1])
dataframe

0
25  a
24  b
23  c
22  e
21  d
20  f
19  g
18  h
17  i
16  j
15  k
14  l
13  m
12  n
11  o
10  p
9   q
8   r
7   s
6   t
5   u
4   v
3   w
2   x
1   y
0   z

In [55]:
#13) ¿Como combinar varias series para hacer un DataFrame?
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

dataframe_varias_series = pd.DataFrame({'Serie1':ser1,'Serie 2':ser2})
dataframe_varias_series

Serie1  Serie 2
0       a        0
1       b        1
2       c        2
3       e        3
4       d        4
5       f        5
6       g        6
7       h        7
8       i        8
9       j        9
10      k       10
11      l       11
12      m       12
13      n       13
14      o       14
15      p       15
16      q       16
17      r       17
18      s       18
19      t       19
20      u       20
21      v       21
22      w       22
23      x       23
24      y       24
25      z       25

In [59]:
#14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
indices_en_serie1 = ser1.isin(ser2)
ser1[np.invert(indices_en_serie1)]

0    1
1    2
2    3
dtype: int64

In [63]:
#15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
indices_ser1_no_ser2 = ser1.isin(ser2)
indices_ser2_no_ser1 = ser2.isin(ser1)
valores_dif_ser1 = ser1[np.invert(indices_ser1_no_ser2)]
valores_dif_ser2 = ser2[np.invert(indices_ser2_no_ser1)]
valores_no_comunes = pd.concat([valores_dif_ser1, valores_dif_ser2])
valores_no_comunes

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

In [65]:
#16) ¿Como obtener el numero de veces que se repite un valor en una serie?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
veces_se_repite = ser.value_counts()
veces_se_repite

g    8
e    6
h    4
b    3
f    3
d    3
a    2
c    1
dtype: int64

In [70]:
#17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(ser)
veces_se_repite = ser.value_counts()
print(veces_se_repite)


0     4
1     3
2     1
3     3
4     1
5     4
6     3
7     1
8     2
9     4
10    4
11    4
dtype: int32
4    5
3    3
1    3
2    1
dtype: int64


In [82]:
#18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?
ser = pd.Series(np.random.randint(1, 10, 35))
arr_np = np.array(ser)
dataframe_shape = pd.DataFrame(arr_np.reshape(7,5))
dataframe_shape
#shape(7,5)

0  1  2  3  4
0  3  6  2  7  9
1  1  6  7  3  8
2  1  1  1  3  5
3  3  7  6  3  2
4  1  8  9  6  7
5  4  8  1  8  7
6  9  6  4  4  4

In [84]:
#19) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [86]:
#20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser11 = pd.Series(range(5))
ser22 = pd.Series(list('abcde'))
data_frame_horizontal = pd.DataFrame()
data_frame_horizontal = data_frame_vertical.append(ser11, ignore_index=True)
data_frame_horizontal

NameError: name 'data_frame_vertical' is not defined

In [88]:
#21)¿Obtener la media de una serie agrupada por otra serie? groupby tambien esta disponible en series.

frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'manzana', 'banana', 'manzana', 'manzana', 'zanahoria', 'manzana', 'zanahoria', 'banana', 'zanahoria']


In [90]:
#22)¿Como importar solo columnas especificas de un archivo csv?
data = './BostonHousing.csv'
docimento=pd.read_csv(data)
df = pd.DataFrame(docimento)
df = df[['crim','rad','tax']]
print(df)

        crim  rad  tax
0    0.00632    1  296
1    0.02731    2  242
2    0.02729    2  242
3    0.03237    3  222
4    0.06905    3  222
..       ...  ...  ...
501  0.06263    1  273
502  0.04527    1  273
503  0.06076    1  273
504  0.10959    1  273
505  0.04741    1  273

[506 rows x 3 columns]
