In [3]:
# pip install numpy
# conda install numpy
import numpy as np

In [30]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [29]:
np.zeros(5) # 1 solo numero para un arreglo
np.zeros([5,5]) # 1 lista o tupla para una matriz de n dimensiones
np.zeros((5,5))
np.zeros([2,2,2])
np.zeros([1000,200])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
np.ones(7)
np.ones([1,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.eye(10) #matriz identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.arange(5) #un arametro # de elementos

array([0, 1, 2, 3, 4])

In [21]:
np.arange(4,20) #[4, 20[, se puede poner negativos

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(0,20,2) #en el tercer parámetro se pone el salto(puede ser float)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [31]:
len(np.ones(12).reshape(4,3))

4

In [32]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [33]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [34]:
a+b

array([15, 15, 15])

In [35]:
a-b

array([5, 5, 5])

In [36]:
a+7

array([17, 17, 17])

In [37]:
a*b

array([50, 50, 50])

In [38]:
a/2

array([5., 5., 5.])

In [39]:
muestra = np.arange(20).reshape(5,2,2)

array([ 6,  8, 10, 12])

In [52]:
# Mayores a 5 glucosa y menores a 14 y que sean pares
respuesta_glucosa = muestra[(muestra%2==0) & (muestra>5) & (muestra<14)]
respuesta_glucosa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [8]:
B= np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [9]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [10]:
np.dot(A, B)

array([[ 6,  7],
       [26, 31]])

In [4]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arreglo_doce.sum()

66

In [13]:
arreglo_doce.min()

0

In [14]:
arreglo_doce.max()

11

In [16]:
arreglo_doce[5:].sum()

56

In [17]:
arreglo_doce.reshape(3,2,2).sum()

66

In [18]:
arreglo_doce.reshape(3,2,2).sum(axis= 0)

array([[12, 15],
       [18, 21]])

In [19]:
arreglo_doce.reshape(3,2,2).sum(axis= 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [1]:
arreglo_doce.reshape(3,2,2).sum(axis= 2)

NameError: name 'arreglo_doce' is not defined

In [ ]:
arreglo_