In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [5]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
numero_random = np.random.randint(11) # [0, 11[ 
numero_random

7

In [12]:
numero_random_neg = np.random.randint(-9,2)
numero_random_neg

-6

In [19]:
arreglo_random = np.random.randint(10,20,8)
arreglo_random

array([14, 19, 13, 12, 11, 11, 17, 17])

In [15]:
np.random.rand(5)

array([0.02782036, 0.98554227, 0.22640305, 0.98040726, 0.01697068])

In [20]:
np.average(arreglo_random)

14.25

In [21]:
np.mean(arreglo_random)

14.25

In [22]:
np.median(arreglo_random)

13.5

In [23]:
np.std(arreglo_random)

2.8613807855648994

In [24]:
np.var(arreglo_random)

8.1875

In [25]:
arreglo_random.mean()

14.25